// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Z6XClGQDIvBIstzR3OTaqHRyash8Jbk',
    appId: '1:696127665104:web:b5c79098b9df71d4207fd5',
    messagingSenderId: '696127665104',
    projectId: 'meet-up-c3183',
    authDomain: 'meet-up-c3183.firebaseapp.com',
    storageBucket: 'meet-up-c3183.appspot.com',
    measurementId: 'G-SCJTQ52ZFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5Itxofy4SClClWoL5XZquk5879OFZPc',
    appId: '1:696127665104:android:cce50f51126ac295207fd5',
    messagingSenderId: '696127665104',
    projectId: 'meet-up-c3183',
    storageBucket: 'meet-up-c3183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4hfqbXYusg2N5OJNuxqW8grHGVrsqUc',
    appId: '1:696127665104:ios:b85fffd2bd20b85e207fd5',
    messagingSenderId: '696127665104',
    projectId: 'meet-up-c3183',
    storageBucket: 'meet-up-c3183.appspot.com',
    iosClientId: '696127665104-9k2iho17o59c18erb0ikm3emu3mhshjc.apps.googleusercontent.com',
    iosBundleId: 'com.acelucid.meetup.meetUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD4hfqbXYusg2N5OJNuxqW8grHGVrsqUc',
    appId: '1:696127665104:ios:b85fffd2bd20b85e207fd5',
    messagingSenderId: '696127665104',
    projectId: 'meet-up-c3183',
    storageBucket: 'meet-up-c3183.appspot.com',
    iosClientId: '696127665104-9k2iho17o59c18erb0ikm3emu3mhshjc.apps.googleusercontent.com',
    iosBundleId: 'com.acelucid.meetup.meetUp',
  );
}
